//
//  TranslateCountry.swift
//  WeatherForecast
//
//  Created by Jan Hovland on 17/03/2023.
//

import Foundation

func TranslateCountry(country: String) -> String {
    var nation: String = ""
    switch country {
    case "Afghanistan": nation = String(localized: "Afghanistan")
    case "Algeria": nation = String(localized: "Algeria")
    case "American Samoa": nation = String(localized: "American Samoa")
    case "Antarctica": nation = String(localized: "Antarctica")
    case "Antigua and Barbuda": nation = String(localized: "Antigua and Barbuda")
    case "Austria": nation = String(localized: "Austria")
    case "Azerbaijan": nation = String(localized: "Azerbaijan")
    case "Belarus": nation = String(localized: "Belarus")
    case "Belgium": nation = String(localized: "Belgium")
    case "Bosnia and Herzegovina": nation = String(localized: "Bosnia and Herzegovina")
    case "Bouvet Island": nation = String(localized: "Bouvet Island")
    case "Brazil": nation = String(localized: "Brazil")
    case "British Indian Ocean Territory": nation = String(localized: "British Indian Ocean Territory")
    case "British Virgin Islands": nation = String(localized: "British Virgin Islands")
    case "Cambodia": nation = String(localized: "Cambodia")
    case "Cameroon": nation = String(localized: "Cameroon")
    case "Canada": nation = String(localized: "Canada")
    case "Cape Verde": nation = String(localized: "Cape Verde")
    case "Caribbean Netherlands": nation = String(localized: "Caribbean Netherlands")
    case "Cayman Island": nation = String(localized: "Cayman Island")
    case "Central African Republic": nation = String(localized: "Central African Republic")
    case "Chad": nation = String(localized: "Chad")
    case "China": nation = String(localized: "China")
    case "Christmas Island": nation = String(localized: "Christmas Island")
    case "Cocos (Keeling) Islands": nation = String(localized: "Cocos (Keeling) Islands")
    case "Comoros": nation = String(localized: "Comoros")
    case "Cook Islands": nation = String(localized: "Cook Islands")
    case "Croatia": nation = String(localized: "Croatia")
    case "Cyprus": nation = String(localized: "Cyprus")
    case "Czechia": nation = String(localized: "Czechia")
    case "DR Congo": nation = String(localized: "DR Congo")
    case "Denmark": nation = String(localized: "Denmark")
    case "Deutschland": nation = String(localized: "Deutschland")
    case "Dominican Republic": nation = String(localized: "Dominican Republic")
    case "Equatorial Guinea": nation = String(localized: "Equatorial Guinea")
    case "Estonia": nation = String(localized: "Estonia")
    case "Ethiopia": nation = String(localized: "Ethiopia")
    case "Falkland Islands": nation = String(localized: "Falkland Islands")
    case "Faroe Islands": nation = String(localized: "Faroe Islands")
    case "France": nation = String(localized: "France")
    case "French Guiana": nation = String(localized: "French Guiana")
    case "French Polynesia": nation = String(localized: "French Polynesia")
    case "French Southern and Antarctic Lands": nation = String(localized: "French Southern and Antarctic Lands")
    case "Germany": nation = String(localized: "Germany")
    case "Greece": nation = String(localized: "Greece")
    case "Greenland": nation = String(localized: "Greenland")
    case "Hungary": nation = String(localized: "Hungary")
    case "Iceland": nation = String(localized: "Iceland")
    case "Iraq": nation = String(localized: "Iraq")
    case "Ireland": nation = String(localized: "Ireland")
    case "Italy": nation = String(localized: "Italy")
    case "Ivory Coast": nation = String(localized: "Ivory Coast")
    case "Kazakhstan": nation = String(localized: "Kazakhstan")
    case "Kyrgyzstan": nation = String(localized: "Kyrgyzstan")
    case "Lebanon": nation = String(localized: "Lebanon")
    case "Lithuania": nation = String(localized: "Lithuania")
    case "Madagascar": nation = String(localized: "Madagascar")
    case "Maldives": nation = String(localized: "Maldives")
    case "Marshall Islands": nation = String(localized: "Marshall Islands")
    case "Micronesia": nation = String(localized: "Micronesia")
    case "Morocco": nation = String(localized: "Morocco")
    case "Mozambique": nation = String(localized: "Mozambique")
    case "Netherlands": nation = String(localized: "Netherlands")
    case "New Caledonia": nation = String(localized: "New Caledonia")
    case "Norfolk Island": nation = String(localized: "Norfolk Island")
    case "North Korea": nation = String(localized: "North Korea")
    case "North Macedonia": nation = String(localized: "North Macedonia")
    case "Northern Mariana Islands": nation = String(localized: "Northern Mariana Islands")
    case "Norway": nation = String(localized: "Norway")
    case "Palestine": nation = String(localized: "Palestine")
    case "Papua New Guinea": nation = String(localized: "Papua New Guinea")
    case "Philippines": nation = String(localized: "Philippines")
    case "Pitcairn Islands": nation = String(localized: "Pitcairn Islands")
    case "Poland": nation = String(localized: "Poland")
    case "Republic of the Congo": nation = String(localized: "Republic of the Congo")
    case "Russia": nation = String(localized: "Russia")
    case "Saint Barthélemy": nation = String(localized: "Saint Barthélemy")
    case "Saint Helena, Ascension and Tristan da": nation = String(localized: "Saint Helena, Ascension and Tristan da")
    case "Saint Kitts and Nevis": nation = String(localized: "Saint Kitts and Nevis")
    case "Saudi Arabia": nation = String(localized: "Saudi Arabia")
    case "Seychelles": nation = String(localized: "Seychelles")
    case "Solomon Islands": nation = String(localized: "Solomon Islands")
    case "South Africa": nation = String(localized: "South Africa")
    case "South Georgia": nation = String(localized: "South Georgia")
    case "South Korea": nation = String(localized: "South Korea")
    case "South Sudan": nation = String(localized: "South Sudan")
    case "Spain": nation = String(localized: "Spain")
    case "Suriname": nation = String(localized: "Suriname")
    case "Svalbard and Jan Mayen": nation = String(localized: "Svalbard and Jan Mayen")
    case "Sweden": nation = String(localized: "Sweden")
    case "Switzerland": nation = String(localized: "Switzerland")
    case "São Tomé and Príncipe": nation = String(localized: "São Tomé and Príncipe")
    case "Tajikistan": nation = String(localized: "Tajikistan")
    case "Timor-Leste": nation = String(localized: "Timor-Leste")
    case "Trinidad and Tobago": nation = String(localized: "Trinidad and Tobago")
    case "Turkey": nation = String(localized: "Turkey")
    case "Turks and Caicos Islands": nation = String(localized: "Turks and Caicos Islands")
    case "Ukraine": nation = String(localized: "Ukraine")
    case "United Arab Emirates": nation = String(localized: "United Arab Emirates")
    case "United Kingdom": nation = String(localized: "United Kingdom")
    case "United States": nation = String(localized: "United States")
    case "United States Minor Outlying Islands": nation = String(localized: "United States Minor Outlying Islands")
    case "United States Virgin Islands": nation = String(localized: "United States Virgin Islands")
    case "Uzbekistan": nation = String(localized: "Uzbekistan")
    case "Vatican City": nation = String(localized: "Vatican City")
    case "Wallis and Futuna": nation = String(localized: "Wallis and Futuna")
    case "Western Sahara": nation = String(localized: "Western Sahara")
    case "Yemen": nation = String(localized: "Yemen")
    case "Åland Islands": nation = String(localized: "Åland Islands")
    default: nation = country
    }
    return nation
}
